### ISSUE TITLE
build error simulate_crash_mac

### ISSUE THREAD

**Issue by vibber** [vade/chromium#9]
Hi I would like some help deciphering an error message from ninja. I am not trained in deciphering these:

```
[4778/29298] CXX obj/third_party/crash...pad/client/client/simulate_crash_mac.o
FAILED: obj/third_party/crashpad/crashpad/client/client/simulate_crash_mac.o 
../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -MF obj/third_party/crashpad/crashpad/client/client/simulate_crash_mac.o.d -DV8_DEPRECATION_WARNINGS -DNO_TCMALLOC -DFULL_SAFE_BROWSING -DSAFE_BROWSING_CSD -DSAFE_BROWSING_DB_LOCAL -DCHROMIUM_BUILD -DFIELDTRIAL_TESTING_ENABLED -DCR_CLANG_REVISION=\"303369-1\" -DCR_XCODE_VERSION=0920 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -DCOMPONENT_BUILD -D__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORE=0 -D_DEBUG -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DWTF_USE_DYNAMIC_ANNOTATIONS=1 -I../.. -Igen -I../../third_party/crashpad/crashpad -I../../third_party/crashpad/crashpad/compat/non_win -I../../third_party/crashpad/crashpad/compat/mac -I../../third_party/crashpad/crashpad/compat/non_cxx11_lib -fno-strict-aliasing -fstack-protector-strong -Wno-builtin-macro-redefined -D__DATE__= -D__TIME__= -D__TIMESTAMP__= -fcolor-diagnostics -arch x86_64 -Wall -Werror -Wextra -Wpartial-availability -Wno-missing-field-initializers -Wno-unused-parameter -Wno-c++11-narrowing -Wno-covered-switch-default -Wno-unneeded-internal-declaration -Wno-inconsistent-missing-override -Wno-undefined-var-template -Wno-nonportable-include-path -Wno-address-of-packed-member -Wno-unused-lambda-capture -Wno-user-defined-warnings -O0 -fno-omit-frame-pointer -gdwarf-2 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -mmacosx-version-min=10.9 -fvisibility=hidden -Xclang -load -Xclang ../../third_party/llvm-build/Release+Asserts/lib/libFindBadConstructs.dylib -Xclang -add-plugin -Xclang find-bad-constructs -Xclang -plugin-arg-find-bad-constructs -Xclang check-auto-raw-pointer -Wheader-hygiene -Wstring-conversion -Wtautological-overlap-compare -Wno-undefined-bool-conversion -Wno-tautological-undefined-compare -std=c++11 -stdlib=libc++ -fno-rtti -fno-exceptions -fvisibility-inlines-hidden -c ../../third_party/crashpad/crashpad/client/simulate_crash_mac.cc -o obj/third_party/crashpad/crashpad/client/client/simulate_crash_mac.o
In file included from ../../third_party/crashpad/crashpad/client/simulate_crash_mac.cc:20:
../../base/logging.h:747:26: error: comparison of integers of different signs: 'const unsigned int' and 'const int' [-Werror,-Wsign-compare]
DEFINE_CHECK_OP_IMPL(EQ, ==)
~~~~~~~~~~~~~~~~~~~~~~~~~^~~
../../base/logging.h:736:33: note: expanded from macro 'DEFINE_CHECK_OP_IMPL'
    if (ANALYZER_ASSUME_TRUE(v1 op v2))                                      \
                             ~~ ^  ~~
../../base/logging.h:327:36: note: expanded from macro 'ANALYZER_ASSUME_TRUE'
#define ANALYZER_ASSUME_TRUE(arg) (arg)
                                   ^~~
../../third_party/crashpad/crashpad/client/simulate_crash_mac.cc:185:3: note: in instantiation of function template specialization 'logging::CheckEQImpl<unsigned int, int>' requested here
  DCHECK_EQ(cpu_context.tsh.flavor,
  ^
../../base/logging.h:923:31: note: expanded from macro 'DCHECK_EQ'
#define DCHECK_EQ(val1, val2) DCHECK_OP(EQ, ==, val1, val2)
                              ^
../../base/logging.h:877:18: note: expanded from macro 'DCHECK_OP'
      ::logging::Check##name##Impl((val1), (val2),                     \
                 ^
<scratch space>:82:1: note: expanded from here
CheckEQImpl
^
1 error generated.
[4787/29298] CXX obj/third_party/crash...pad/handler/handler_lib/handler_main.o
```

**Comment by vibber** [comment]
Update: I think I'll try to build with the 10.12 SDK. Was running with the 10.13 SDK when this happened

**Comment by vibber** [comment]
The solution is to download Xcode 8.3.3 from Apple Developer Connection. Put it next to the other Xcode in Applications
Then: 

`sudo xcode-select -s /Applications/Xcode8.3.3.app/`

then in src dir

`gn gen out/Default`

and compile with

`ninja -C out/Default chrome`
